services:
  pyimage-service:
    build: 
      context: .
      dockerfile: server/Dockerfile
    image: aisentinel-backend:latest
    container_name: server-pyimage-aisentinel
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./server:/app
      - /app/venv
      - ./server/chroma_data:/app/chroma_data
    env_file:
      - .env
    restart: always
